Repository CoffeeShopTeam/CoffeeShopRepo, pull requests merged in 2023-07, with the labels that each got.

#105 dynamic-page/cart
  backend/index.js
  backend/models/orders/order.validator.js
  backend/models/orders/orders.schema.js
  backend/package.json
  backend/routes/account.routes.js
  backend/routes/cart.routes.js
  backend/routes/index.js
  backend/tests/addUser.test.js
  backend/tests/cart.routes.test.js
  backend/views/Cart/Cart.css
  backend/views/Cart/Cart.ejs
  backend/views/Cart/Cart.js
  backend/views/ProductPage/productPage.ejs
  backend/views/ProductPage/productPage.js
  backend/views/account/account.ejs
  backend/views/account/accountDetails/accountDetails.ejs
  backend/views/assets/ShlomkePic.png
  backend/views/checkout/Checkout.ejs
  backend/views/partials/Footer/Footer.html
  backend/views/partials/Header/Header.html
Labels: cr

#109 general-changes
  backend/views/homePage/homePage.ejs
Labels: done

#124 Quantity problem
  backend/controller/orders/orders.controller.js
  backend/models/products/product.schema.js
  backend/models/products/product.validator.js
  backend/routes/cart.routes.js
  backend/routes/checkout.routes.js
  backend/routes/orders.routes.js
  backend/views/Cart/Cart.ejs
  backend/views/Cart/Cart.js
  backend/views/ProductPage/productPage.css
  backend/views/ProductPage/productPage.ejs
  backend/views/ProductPage/productPage.js
  backend/views/ShopPage/ShopPage.css
  backend/views/ShopPage/ShopPage.ejs
  backend/views/checkout/Checkout.ejs
  backend/views/login/loginPage.js
Labels: done

#127 fix view order bug
  backend/controller/orders/orders.controller.js
  backend/controller/products/products.controller.js
  backend/routes/account.routes.js
  backend/routes/orderConfirmation.routes.js
  backend/services/exchangeRate/exchangeRate.js
  backend/views/account/accountViewOrder/accountViewOrder.ejs
Labels: in progress
